### PR TITLE
Fix incorrect handling of output buffer for `wp_head` action when stacked buffers are used

### LINKED ISSUE #28: Incompatible with `/wp/v2/widget-types/:id/render`
The REST API Endpoint `/wp/v2/widget-types/<widget>/render` returns an iframe template which uses `wp_head();`

https://github.com/WordPress/wordpress-develop/blob/6.0/src/wp-includes/rest-api/endpoints/class-wp-rest-widget-types-controller.php#L613-L655

As h2push hooks into `wp_head`, which causes the whole header to be added before the JSON output.

### PR DESCRIPTION
**Pull request by ocean90**
Alternative for #29.

Fixes #28.

### CODE REVIEW

File: h2push.php [hunk 1]
```diff
@@ -51,7 +51,7 @@ function start_output_buffer(): void {
  */
 function stop_output_buffer(): void {
 	if ( ob_get_length() ) {
-		ob_flush();
+		echo ob_get_clean(); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
```
Comment (grappler) [inline h2push.php:54]: Wieso verwenden wir `ob_end_flush()` nicht?
```suggestion
		ob_end_flush();
```

**Review by grappler — APPROVED** [review]
